name: Build

on: 
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: 0 23 * * 5

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    #if: github.repository_owner=='a0575'
    env:
      build_variant: ${{ matrix.build_variant }}
      targets: ${{ matrix.targets }}
      images_dir: /opt/images
    strategy:
      matrix:
        include:
          - build_variant: "A1"
            targets: "PSG1208 PSG1218 NEWIFI-MINI MI-MINI MI-3 MI-4 OYE-001 5K-W20 DIR-878 DIR-882 E8820V2 JCG-Y2 K2P"
          - build_variant: "A2"
            targets: "HC5861B MI-NANO MZ-R13 MZ-R13P 360P2 HC5761A HC5661A K2P_nano MR2600 MR2600-5.0 JCG-836PRO"
          - build_variant: "A3"
            targets: "K2P_nano-5.0 K2P-5.0 DIR-878-5.0 RM2100 PSG1218_nano RT-AC1200GU WDR7300 JCG-AC860M K2P-USB-5.0 K2P-USB CR660x"
          - build_variant: "A4"
            targets: "XY-C1 JCG-836PRO-5.0 JCG-AC860M-5.0 JCG-Y2-5.0 DIR-882-5.0 A3004NS MSG1500 WR1200JS MI-R3G NEWIFI3 B70"
          - build_variant: "A5"
            targets: "MI-3C MI-R3P MI-R3P-breed MI-R4A NETGEAR-BZV NETGEAR-CHJ R2100 R6220 ZTE_E8820S"
          - build_variant: "A6"
            targets: "GHL JCG-AC836M JCG-AC856M-5.0 JDC-1-5.0 JDC-1 K2P-USB-512 MSG1500-7615 MZ-R18 NEWIFI-D1 PSG712 RE6500 YK-L1"
            
    steps:

      - name: Checkout
        uses: actions/checkout@master
      
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install libtool-bin gperf python-docutils autopoint gettext
        
      - name: Run shellcheck
        run: |
          cp -r scripts/. trunk/
          sh ./trunk/tools/shellcheck.sh
        
      - name: Prepare toolchain
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh
        
      - name: Start build
        run: |
          cd trunk
          mkdir -p ${images_dir}
          for m in $targets; do fakeroot ./build_firmware_ci $m; \
          if [ $? = 0 ]; then cp -f images/*.trx ${images_dir}/$m.trx; else exit 1; fi; \
            ./clear_tree_simple >/dev/null 2>&1; done
            
      - name: Create archive
        if: ${{ github.event_name != 'release' && success() }}
        run: |
          GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ] && \
          image_name=images_${build_variant}_${GIT_VERSION} || image_name=images_${build_variant}
          cd /opt/images; md5sum *.trx |tee md5sum.txt; 7z a -mx=9 ${image_name}.7z ./*
          echo "image_name=${image_name}" >> $GITHUB_ENV
          
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::padavan_$(date +%Y-%m-%d)"
          touch release.txt
          echo "::set-output name=status::success"
        
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.workflow_token }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: /opt/images/*.trx
