name: Update trunk

on:

  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04
    if: github.repository_owner=='a0575'
    
    steps:

      - name: Checkout
        uses: actions/checkout@master
        
      - name: 复制
        run: svn co https://github.com/hanwckf/rt-n56u/trunk/trunk new 
          
          
      - name: 整理
        run: | 
          cp -r new/. trunk/
          rm -rf new
        
      - name: 提交
        run: git commit -am 'Auto Update'
          
        
      - name: 更新
        run: git push
