name: Update trunk

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04
    if: github.repository_owner=='a0575'
    
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: 设置帐户
        run: git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

      - name: 复制
        run: svn co https://github.com/hanwckf/rt-n56u/trunk/trunk new 
 
      - name: 整理
        run: | 
          cp -r new/. trunk/
          rm -rf new
          rm -rf trunk/.svn

      - name: 添加文件到暂存区
        run: git add .
             
      - name: 暂存区全部文件替换工作区
        run: git checkout .

      - name: 提交
        run: git commit -am 'Auto Update'

      - name: 更新
        run: git push
