name: Update trunk

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository_owner=='a0575'
    
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: 设置帐户
        run: git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

      - name: 复制
        run: |
          svn export https://github.com/hanwckf/rt-n56u/trunk/trunk new
          #svn export https://github.com/hanwckf/rt-n56u/trunk/toolchain-mipsel new1
      
      - name: 整理
        run: | 
          cp -r new/. trunk/
          cp -r scripts/. trunk/
          rm -rf new
          sed '9c\PROJECT_HOME_URL="https:\/\/https:\/\/github.com\/a0575\/padavan\/" trunk/user/www/Makefile
          sed '10c\PROJECT_HOME_URL_MOD="https:\/\/https:\/\/github.com\/a0575\/padavan\/" trunk/user/www/Makefile
          sed '12c\LABEL_COPYRIGHT_TEXT='© 2020-2021 <a href="https:\/\/https:\/\/github.com\/a0575\/padavan\/" target="blank">Padavan<\/a> \& N56U project community \& by <a href="https:\/\/https:\/\/github.com\/a0575\/padavan\/" target="blank">github<\/a>' trunk/user/www/Makefile

      - name: 添加文件到暂存区
        run: git add .
             
      #- name: 暂存区全部文件替换工作区
        #run: git checkout .

      - name: 提交
        run: git commit -am 'Auto Update'

      - name: 更新
        run: git push
